version: '3'
services:

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  balancer:
    build: ""  #path to balancer
    ports:
      - "3000:80"
    depends_on:
      - app
    links:
      - app:app

  app:
    build: "" #path to web
    ports:
      - "3005:3000"
    environment:
      - port=3000
    depends_on:
      - redis
    links:
      - redis
