version: '3'
services:

  redis:
    image: "redis"

  balancer:
    build: ./docker_images/Nginx/  
    ports:
      - "3000:80"
    depends_on:
      - app1
      - app2
    links:
      - app1
      - app2

  app1:
    build: ./
    environment:
      - port=3000
    depends_on:
      - redis
    links:
      - redis

  app2:
    build: ./
    environment:
      - port=3000
    depends_on:
      - redis
    links:
      - redis
